import type { Metadata } from "next";
import "./ui/globals.css";
import { inter, cairo } from "@/app/ui/fonts";
import Header from "@/app/ui/components/Header/Header";
import Footer from "@/app/ui/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
